name = "kodesiana-pendekin"
main = "src/index.ts"
compatibility_date = "2023-12-23"

kv_namespaces = [
  { binding = "SHORT_URLS", id = "1268ed17e5864c38b6ccaf7e36332127" },
  { binding = "SHORT_URL_STATS", id = "4ed2362d1a2d417eb1226dae2f71ddf1" }
]

[vars]
HOST_URL = "https://l.kodesiana.com"
HOMEPAGE_URL = "https://www.kodesiana.com"
